version: '3.4'

x-defaults: &defaults
  restart: always
  build:
    context: .
    args:
      SENTRY_IMAGE: ${SENTRY_IMAGE}
  depends_on:
    - redis
    - postgres
    - memcached
    - smtp
  env_file: .env
  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    SENTRY_EMAIL_HOST: smtp
  volumes:
    - sentry-data:/var/lib/sentry/files


services:
  smtp:
    restart: always
    image: tianon/exim4

  memcached:
    restart: always
    image: memcached:1.5-alpine

  redis:
    restart: always
    image: redis:3.2-alpine

  postgres:
    restart: always
    image: postgres:9.5
    volumes:
      - sentry-postgres:/var/lib/postgresql/data

  web:
    <<: *defaults

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker

  nginx:
    # set NGINX_DOMAIN env var
    restart: always
    build:
      context: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - '80:80'
      - '443:443'
    command: /bin/sh -c "envsubst '$$NGINX_DOMAIN' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

volumes:
    sentry-data:
      external: true
    sentry-postgres:
      external: true
